### PR TITLE
Attempt to associate with eclipse+mpc URIs

### PR DESCRIPTION
**Pull request by mickaelistria**
Closes https://github.com/flathub/org.eclipse.Java/issues/7
Closes https://github.com/flathub/org.eclipse.Java/issues/10

### CODE REVIEW

**Comment by BeckerWdf** [comment]
This change hard-codes the eclipse+mpc uri scheme. But the uri schemes are extendable  in eclipse. Plugins  can contribute handlers for their own scheme. The preference page takes care to register them on the operating system (using a .desktop file on linux, using the registry on windows and using the info.plist file together with a call to lsrgister on macOS). You should find a way to make this registration also working for the flatpack use-case.

**Comment by akurtakov** [comment]
> This change hard-codes the eclipse+mpc uri scheme. But the uri schemes are extendable in eclipse. Plugins can contribute handlers for their own scheme. The preference page takes care to register them on the operating system (using a .desktop file on linux, using the registry on windows and using the info.plist file together with a call to lsrgister on macOS). 

Would you please explain how does the .desktop file registration works on Linux? Eclipse is not shipping desktop file and desktop files don't allow "dynamic" content AFAIK.

**Comment by BeckerWdf** [comment]
See the RegistrationLinux class in the org.eclipse.urischeme bundle.

**Comment by akurtakov** [comment]
Patch conflicts. What is the status here? Is there a reason to not support eclipse+mpc and let dynamic handlers be considered later?

**Pull request merged**
