### PR TITLE
Add release 4.29 metadata

### PR DESCRIPTION
**Pull request by gredler**
Adds missing 4.29 release metadata.

### CODE REVIEW

**Comment by gredler** [comment]
@akurtakov Is there anything else needed, or does this look good? Thanks!

**Comment by akurtakov** [comment]
Looks good. Thanks. 
For the record - I'm looking for someone to take over tasks like this one so if anyone has interest please contact me, I just can't promise to do things in timely manner.

**Comment by Mailaender** [comment]
I am interested in maintaining the Eclipse Flatpak.

**Comment by akurtakov** [comment]
@Mailaender You should be able to handle to update to 4.30 now.

**Pull request merged**
