### PR TITLE
Added no-debuginfo build option

### PR DESCRIPTION
**Pull request by Stargazer3240**
With this flag, I managed to run flatpak-builder with success.

### CODE REVIEW

**Comment by akurtakov** [comment]
Thanks for the patch! Much appreciated!

**Comment by akurtakov** [comment]
@Stargazer3240 , are you interested in being added as committer here so you can help with updates in the future too?

**Comment by Stargazer3240** [comment]
> @Stargazer3240 , are you interested in being added as committer here so you can help with updates in the future too?

Thanks for the offer, but I'm not interest. I'm just using eclipse for a course at college.

**Comment by akurtakov** [comment]
> > @Stargazer3240 , are you interested in being added as committer here so you can help with updates in the future too?
> 
> Thanks for the offer, but I'm not interest. I'm just using eclipse for a course at college.

Thanks for the spending the time in this case! I hope you enjoy using Eclipse for long time.

**Pull request merged**
